version: '3.7'
services:
  traefik:
    image: traefik:latest
    container_name: yuuyu-Traefik
    command:
      - "--certificatesresolvers.yuuyuresolver.acme.tlschallenge=true"
      - "--providers.docker=true"
    volumes:
      - ./data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.yuuyu.dev`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=yuuyuresolver"
      - "traefik.http.middlewares.traefik.basicauth.users=${BASIC_AUTH}"
    networks:
      - yuuyu-network
    restart: always
networks:
  yuuyu-network:
    external: true
