version: '3.7'
services:
  traefik:
    image: traefik:latest
    container_name: yuuyu-Traefik
    volumes:
      - ./data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8000:8000
    networks:
      - yuuyu-network
    restart: always
networks:
  yuuyu-network:
    external: true
